image: docker:latest

variables:
  DOCKER_DRIVER: overlay2
  GIT_STRATEGY: none

services:
  - docker:dind

stages:
  - docs

pages:
  image: python:3.6-slim
  stage: docs
  variables:
    GIT_DEPTH: 5
    GIT_STRATEGY: fetch
  script:
    - apt-get update && apt-get install -y build-essential
    - pip install poetry
    - poetry config settings.virtualenvs.create false
    - poetry install --no-dev --no-interaction --no-ansi
    - pip install sphinx
    - cd docs
    - make html
    - mv _build/html public
  artifacts:
    paths:
      - public



